const DB_NAME='genzhuoshuo-audio-v1', STORE='sentenceAudio', DRAFT_KEY='genzhuoshuo-draft-v1', DRAFTS_KEY='genzhuoshuo-drafts-v1', DIR_KEY='__audio-directory__';
const app=document.querySelector('#app'), toastEl=document.querySelector('#toast');
let state={screen:'home',draftId:null,title:'我的第一条口播',text:'',source:'my-voice',sentences:[],index:0,recording:false,media:null,activeAudio:null,recognition:null,stream:null,micStream:null,startedAt:0,timer:null,elapsed:0,micLevel:0,studioPlaying:false,directoryHandle:null,promptUrls:{},audioUnlocked:false};
const $=(s,r=document)=>r.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function notify(msg){toastEl.textContent=msg;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),2600)}
function db(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function putAudio(key,blob){const d=await db();return new Promise((res,rej)=>{const t=d.transaction(STORE,'readwrite');t.objectStore(STORE).put(blob,key);t.oncomplete=res;t.onerror=()=>rej(t.error)})}
async function getAudio(key){const d=await db();return new Promise((res,rej)=>{const t=d.transaction(STORE);const r=t.objectStore(STORE).get(key);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function putMeta(key,value){const d=await db();return new Promise((res,rej)=>{const t=d.transaction(STORE,'readwrite');t.objectStore(STORE).put(value,key);t.oncomplete=res;t.onerror=()=>rej(t.error)})}
async function getMeta(key){const d=await db();return new Promise((res,rej)=>{const t=d.transaction(STORE);const r=t.objectStore(STORE).get(key);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function draftData(){return {id:state.draftId,title:state.title,text:state.text,source:state.source,sentences:state.sentences,createdAt:state.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()}}
function persist(){const d=draftData();localStorage.setItem(DRAFT_KEY,JSON.stringify(d));let all=[];try{all=JSON.parse(localStorage.getItem(DRAFTS_KEY)||'[]')}catch(e){}const i=all.findIndex(x=>x.id===d.id);if(i<0)all.unshift(d);else all[i]=d;localStorage.setItem(DRAFTS_KEY,JSON.stringify(all))}
function load(){try{const x=JSON.parse(localStorage.getItem(DRAFT_KEY));if(x){if(!x.id)x.id=`legacy-${Date.now()}`;state={...state,...x};let all=drafts();if(!all.some(d=>d.id===x.id)){all.unshift(x);localStorage.setItem(DRAFTS_KEY,JSON.stringify(all));}}}catch(e){};getMeta(DIR_KEY).then(x=>state.directoryHandle=x||null).catch(()=>{})}
function drafts(){try{return JSON.parse(localStorage.getItem(DRAFTS_KEY)||'[]')}catch(e){return []}}
function fmtDate(v){return new Date(v).toLocaleDateString('zh-CN',{year:'numeric',month:'numeric',day:'numeric'})}
function home(){let list=drafts();return `<section class="home-head"><div><div class="eyebrow">Your scripts</div><h1>我的稿件</h1><p>每一篇口播，都是一套属于你的声音提示。</p></div><button class="primary" id="newDraft">＋ 新建稿件</button></section><section class="catalog">${list.length?list.map(d=>`<article class="script-card"><button class="card-open" data-open="${d.id}"><div class="card-top"><span class="script-dot">◉</span><span class="more">···</span></div><h2>${esc(d.title)}</h2><div class="card-meta"><span>${fmtDate(d.createdAt)}</span><span>${d.sentences?.length||0} 段文字</span><span>${d.sentences?.filter(s=>s.audioKey).length||0} 段录音</span></div><div class="card-progress"><b style="width:${d.sentences?.length?d.sentences.filter(s=>s.recordingStatus==='已确认').length/d.sentences.length*100:0}%"></b></div></button><button class="delete-script" data-delete="${d.id}">删除稿件</button></article>`).join(''):'<div class="empty panel"><div class="empty-icon">◌</div><h2>还没有稿件</h2><p>新建第一篇稿件，开始录下你的声音。</p><button class="secondary" id="newDraftEmpty">＋ 新建稿件</button></div>'}</section><div class="folder-bar"><span>⌁ 录音保存位置：${state.directoryHandle?'已连接本机文件夹（录音直接保存在这里）':'尚未选择文件夹'}</span><button class="ghost" id="chooseFolder">选择录音文件夹</button></div>`}
function settings(){const endpoint=state.asrEndpoint||asrEndpoint();return `${flow('')}<section class="hero"><div class="eyebrow">Connection</div><h1>ASR 配置</h1><p>为这台设备配置 ASR 服务地址。API Key 只应放在服务端，网页不会保存或上传密钥。</p></section><section class="panel settings-panel"><div class="label-row"><span class="label">ASR 服务地址</span><span class="hint">每位用户可单独配置</span></div><input id="asrEndpointInput" class="input-line" value="${esc(endpoint)}" placeholder="https://your-domain.com/api/asr"/><p class="settings-help">服务需要接受 <code>POST</code> 音频请求，并返回火山 ASR 结果 JSON。跨域部署时请允许当前网站的 CORS 请求。</p><div class="settings-status" id="asrConfigStatus">${state.asrEndpoint?'当前使用自定义地址':'当前使用本地默认代理地址'}</div><div class="actions"><button class="ghost" id="settingsBack">← 返回</button><div><button class="secondary" id="resetAsr">恢复默认</button> <button class="primary" id="saveAsr">保存配置</button></div></div></section>`}
function splitText(t){return t.split(/\n+|(?<=[。！？!?；;])\s*/).map(x=>x.trim()).filter(Boolean)}
function flow(active){return `<div class="flow"><span class="${active==='editor'?'active':''}">01 稿件</span><span class="${active==='recorder'?'active':''}">02 录制提示音</span><span class="${active==='review'?'active':''}">03 录音检查</span><span class="${active==='studio'?'active':''}">04 正式口播</span></div>`}
function editor(){return `${flow('editor')}<section class="hero"><div class="eyebrow">Your voice, your rhythm</div><h1>让每一句话，<br>都跟着你的节奏。</h1><p>提前录下自己的声音，正式拍摄时通过耳机逐句提示。自然表达，不再低头看稿。</p></section><section class="two-col"><div class="panel"><div class="label-row"><span class="label">稿件标题</span><span class="hint">自动保存在本机</span></div><input id="title" class="input-line" value="${esc(state.title)}" placeholder="例如：我的第一条口播"/><div class="label-row" style="margin-top:24px"><span class="label">完整口播稿</span><span class="hint">${state.text.length} 字</span></div><textarea id="script" placeholder="把完整稿件粘贴到这里，我们会按句号、问号和换行智能拆分。">${esc(state.text)}</textarea><div class="actions"><span class="hint">支持刷新后继续编辑</span><button class="primary" id="parseBtn">完成分句&nbsp; →</button></div></div><aside class="side-card"><h3>第一版怎么工作？</h3><p>先录下你的声音。每句话单独试听、确认，之后拍摄时耳机播放你的预录音，系统听到你说完再推进。</p><div style="margin-top:25px;font-size:24px">◌　◍　◉</div></aside></section>`}
function choices(){return `<div class="choice-head"><div class="eyebrow">Prompt source</div><h2>正式录制时，你希望怎样听到提示？</h2></div><div class="choice-grid"><button class="choice selected" data-source="my-voice"><span class="tag">推荐</span><div class="choice-icon">◉</div><strong>我的声音</strong><p>最自然 · 需要提前录制一次</p></button><button class="choice disabled" disabled><div class="choice-icon">✦</div><strong>AI 语音</strong><p>准备更快 · 豆包 TTS（即将支持）</p></button><button class="choice disabled" disabled><div class="choice-icon">Aa</div><strong>仅显示文字</strong><p>不需要耳机 · 普通提词器（即将支持）</p></button></div>`}
function render(){if(state.screen==='home')app.innerHTML=home();if(state.screen==='settings')app.innerHTML=settings();if(state.screen==='editor')app.innerHTML=editor()+choices();if(state.screen==='recorder')app.innerHTML=recorder();if(state.screen==='review')app.innerHTML=review();if(state.screen==='studio')app.innerHTML=studio();bind();if(state.screen==='studio'){document.querySelector('.mode-toggle')?.remove();const actions=document.querySelector('.studio-actions');if(actions&&!document.querySelector('#startStudio')){const b=document.createElement('button');b.id='startStudio';b.className='done';b.textContent='▶ 开始口播';actions.prepend(b)}const studioActions=document.querySelector('.studio > .actions');if(studioActions&&!document.querySelector('#studioNext')){const b=document.createElement('button');b.id='studioNext';b.className='ghost';b.textContent='下一句 →';studioActions.insertBefore(b,studioActions.lastElementChild)}const n=document.querySelector('.studio .notice');if(n)n.textContent='电脑：←/→ 切换句子，↑/↓ 或空格重播；手机：左右滑动'}}
function recorder(){let s=state.sentences[state.index]||{};let prev=state.sentences[state.index-1]?.sentenceText||'已经是第一句';let next=state.sentences[state.index+1]?.sentenceText||'已经是最后一句';return `${flow('recorder')}<div class="recorder-top"><div><div class="eyebrow">Record your prompt</div><h1>${esc(state.title)}</h1></div><div class="progress-count">正在录制第 ${state.index+1}/${state.sentences.length} 句</div></div><div class="progress"><b style="width:${(state.index/state.sentences.length)*100}%"></b></div><section class="sentence-stage"><div class="prev">↑ 上一句　${esc(prev)}</div><div class="current">${esc(s.sentenceText)}</div><div class="next">↓ 下一句　${esc(next)}</div><div class="wave ${state.recording?'':'paused'}">${Array.from({length:27},(_,i)=>`<i style="--h:${8+(i*17%25)}px"></i>`).join('')}</div><div class="timer">${formatTime(state.elapsed)}　${state.recording?'● 正在录音':'准备就绪'}</div></section><div class="rec-controls">${!state.recording?`<button class="record-btn" id="startRecord">● 开始录制</button>`:`<button class="record-btn recording" id="stopRecord">■ 停止录制</button>`}<button class="secondary" id="playCurrent" ${s.recordingStatus==='未录制'?'disabled':''}>▶ 试听当前句</button><button class="ghost" id="rerecord">↻ 重录当前句</button></div><div class="actions"><button class="ghost" id="saveExit">退出并保存进度</button>${s.recordingStatus!=='未录制'?`<button class="primary" id="confirmNext">${state.index===state.sentences.length-1?'进入录音检查':'确认并进入下一句'}　→</button>`:''}</div><div class="mic-status" id="micStatus">首次录制会请求麦克风权限。音频仅保存在本机 IndexedDB。</div>`}
function formatTime(ms){let n=Math.floor(ms/1000);return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
function review(){let all=state.sentences.every(s=>s.recordingStatus==='已确认');return `${flow('review')}<div class="review-title"><div><div class="eyebrow">Audio check</div><h1>逐句检查提示音</h1></div><span class="hint">${state.sentences.filter(s=>s.recordingStatus==='已确认').length}/${state.sentences.length} 句已确认</span></div><div class="panel"><div class="actions" style="margin-top:0;margin-bottom:18px"><span class="hint">逐句试听，确保语气和节奏一致</span><div><button class="secondary" id="playAll">▶ 播放全部</button> <button class="ghost" id="confirmAll">全部确认</button></div></div><div class="review-list">${state.sentences.map((s,i)=>`<div class="review-row"><span class="num">${String(i+1).padStart(2,'0')}</span><span class="sentence-text">${esc(s.sentenceText)}</span><span class="duration">${s.duration?formatTime(s.duration):'—'}</span><span class="status ${s.recordingStatus==='已确认'?'confirmed':''}">${s.recordingStatus}</span><span><button class="row-btn" data-play="${i}">▶ 试听</button><button class="row-btn" data-rerecord="${i}">↻ 重录</button></span></div>`).join('')}</div><div class="actions"><button class="ghost" id="backRecord">← 返回录制</button><button class="primary" id="enterStudio" ${all?'':'disabled'}>进入正式口播　→</button></div>${all?'':'<div class="notice danger">请先确认所有句子的录音，才能进入正式口播模式。</div>'}</div>`}
function studio(){let s=state.sentences[state.index]||{};return `${flow('studio')}<section class="studio"><div class="studio-header"><div><div class="eyebrow">Live recording</div><h1>正式口播</h1><span class="hint">${esc(state.title)} · 我的声音提示</span></div><label class="mode-toggle"><input type="checkbox" id="mockToggle" ${state.mock?'checked':''}/> Mock ASR 演示模式</label></div><div class="studio-card"><div class="tiny">CURRENT SENTENCE　${String(state.index+1).padStart(2,'0')} / ${state.sentences.length}</div><h2>${esc(s.sentenceText)}</h2><div class="prompt-state">${state.studioPlaying?'◉ 正在播放你的提示音':'● 等待你开始表达'}</div><div class="studio-actions"><button class="replay" id="replayPrompt">▶ 重播提示音</button><button class="done" id="markDone">我说完了　→</button><button class="stop" id="markIncomplete">没说完整 · 重来</button></div><div class="queue">${state.sentences.map((_,i)=>`<span class="${i===state.index?'current':''}"></span>`).join('')}</div></div><div class="actions"><button class="ghost" id="studioPrev" ${state.index?'':'disabled'}>← 上一句</button><span class="notice">${state.mock?'Mock ASR：用按钮模拟“说完/未说完整”。':'正在使用浏览器语音识别能力。'}</span><button class="ghost" id="studioExit">暂停并退出</button></div></section>`}
async function play(i){stopPlayback();const s=state.sentences[i];const currentKey=`${state.draftId}:${s.sentenceId}`,legacyKey=`${state.title}:${s.sentenceId}`;let u=state.promptUrls[currentKey];if(!u){let blob=await getAudio(currentKey);if(!blob){blob=await getAudio(legacyKey);if(blob){s.audioKey=currentKey;await putAudio(currentKey,blob);persist();}}if(!blob){notify('这句话的录音暂未找到');return}u=URL.createObjectURL(blob);state.promptUrls[currentKey]=u}const a=state.audioPlayer||(state.audioPlayer=new Audio());a.src=u;a.preload='auto';a.playsInline=true;state.activeAudio=a;a.onended=()=>{if(state.activeAudio===a)state.activeAudio=null};await a.play();return a}
function stopPlayback(){if(state.activeAudio){state.activeAudio.pause();state.activeAudio.currentTime=0;state.activeAudio.src='';state.activeAudio=null}state.studioPlaying=false}
function stopRecognition(){if(state.recognition){state.recognition.onresult=null;state.recognition.onend=null;state.recognition.stop();state.recognition=null}}
function goPrevious(){if(state.screen!=='studio'||state.index<=0){notify('已经是第一句');return}stopRecognition();stopPlayback();state.index--;render();if(state.audioUnlocked)playPrompt()}
function goNext(){if(state.screen!=='studio'||state.index>=state.sentences.length-1){notify('已经是最后一句');return}stopRecognition();stopPlayback();state.index++;render();if(state.audioUnlocked)playPrompt()}
function replayCurrent(){if(state.screen!=='studio')return;if(!state.audioUnlocked){notify('请先点击“开始口播”解锁手机音频');return}stopRecognition();stopPlayback();playPrompt()}
function bindMediaControls(){if(!navigator.mediaSession?.setActionHandler)return;try{navigator.mediaSession.setActionHandler('previoustrack',goPrevious);navigator.mediaSession.setActionHandler('nexttrack',goNext)}catch(e){}}
function startCommandRecognition(){if(state.recognition)return;const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition)return;const r=new Recognition();r.lang='zh-CN';r.continuous=true;r.interimResults=false;r.onresult=e=>{for(let i=e.resultIndex;i<e.results.length;i++){if(!e.results[i].isFinal)continue;const t=e.results[i][0].transcript.replace(/\s/g,'');if(t.includes('下一句')){stopRecognition();if(state.liveMedia?.state==='recording')state.liveMedia.stop();advance(true,true);break}if(t.includes('重播')||t.includes('重来一遍')){stopRecognition();if(state.liveMedia?.state==='recording')state.liveMedia.stop();playPrompt();break}if(t.includes('上一句')&&state.index>0){stopRecognition();if(state.liveMedia?.state==='recording')state.liveMedia.stop();stopPlayback();state.index--;render();playPrompt();break}}};r.onerror=()=>{};r.onend=()=>{if(state.screen==='studio'&&!state.studioPlaying)startCommandRecognition()};try{r.start();state.recognition=r}catch(e){}}
window.addEventListener('pagehide',()=>{stopPlayback();stopRecognition();if(state.liveMedia?.state==='recording')state.liveMedia.stop();releaseMic()});
document.addEventListener('click',e=>{if(e.target.closest('#studioExit,#saveExit')){stopPlayback();if(state.liveMedia?.state==='recording')state.liveMedia.stop();releaseMic()}});
document.addEventListener('click',e=>{if(e.target.closest('#startStudio')){const probe=new Audio('data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQAAAAAA');probe.volume=0;probe.play().catch(()=>{});state.audioUnlocked=true;bindMediaControls();playPrompt()}});
document.addEventListener('click',e=>{if(e.target.closest('#studioNext'))goNext()});
document.addEventListener('keydown',e=>{if(state.screen!=='studio'||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;if(e.key==='ArrowLeft'){e.preventDefault();goPrevious()}if(e.key==='ArrowRight'){e.preventDefault();goNext()}if(e.key==='ArrowUp'||e.key==='ArrowDown'||e.code==='Space'||e.key==='r'||e.key==='R'){e.preventDefault();replayCurrent()}});
let touchStartX=0,touchStartY=0;document.addEventListener('touchstart',e=>{if(state.screen==='studio'&&e.touches.length===1&&e.target.closest('.studio-card')){touchStartX=e.touches[0].clientX;touchStartY=e.touches[0].clientY}},{passive:true});document.addEventListener('touchend',e=>{if(state.screen!=='studio'||(!touchStartX&&!touchStartY))return;const dx=e.changedTouches[0].clientX-touchStartX,dy=e.changedTouches[0].clientY-touchStartY;touchStartX=0;touchStartY=0;if(Math.abs(dy)>55&&Math.abs(dy)>Math.abs(dx)){replayCurrent();return}if(Math.abs(dx)>55)(dx<0?goNext:goPrevious)()},{passive:true});
async function chooseFolder(){if(!window.showDirectoryPicker){notify('当前浏览器不支持选择文件夹，将继续使用 IndexedDB 保存');return}try{state.directoryHandle=await showDirectoryPicker({mode:'readwrite'});await putMeta(DIR_KEY,state.directoryHandle);notify('录音文件夹已连接，之后会同时保存 WebM 文件')}catch(e){if(e.name!=='AbortError')notify('无法连接录音文件夹')}}
async function getMicStream(){if(state.micStream?.active)return state.micStream;if(!navigator.mediaDevices?.getUserMedia)throw new Error('当前浏览器不支持麦克风');state.micStream=await navigator.mediaDevices.getUserMedia({audio:true});return state.micStream}
function releaseMic(){state.micStream?.getTracks().forEach(t=>t.stop());state.micStream=null;state.stream=null}
function asrEndpoint(){return state.asrEndpoint|| (location.protocol==='file:'?'http://127.0.0.1:4173/api/asr':'/api/asr')}
if(location.protocol==='file:'){const nativeFetch=window.fetch.bind(window);window.fetch=(input,...rest)=>nativeFetch(input==='/api/asr'?asrEndpoint():input,...rest)}
async function saveToFolder(blob,s){if(!state.directoryHandle)return;try{const permission=await state.directoryHandle.queryPermission({mode:'readwrite'});if(permission!=='granted'&&await state.directoryHandle.requestPermission({mode:'readwrite'})!=='granted')return;const safe=state.title.replace(/[\\/:*?"<>|]/g,'_').slice(0,60)||'未命名稿件';const file=await state.directoryHandle.getFileHandle(`${safe}-${String(s.sentenceIndex+1).padStart(2,'0')}-${s.sentenceId}.webm`,{create:true});const w=await file.createWritable();await w.write(blob);await w.close()}catch(e){notify('文件夹保存失败，已保留本机 IndexedDB 录音')}}
async function deleteDraft(id){const d=drafts().find(x=>x.id===id);if(!d||!confirm(`确定删除稿件“${d.title}”及其全部录音吗？`))return;localStorage.setItem(DRAFTS_KEY,JSON.stringify(drafts().filter(x=>x.id!==id)));if(state.draftId===id){localStorage.removeItem(DRAFT_KEY);state={...state,screen:'home',draftId:null,sentences:[],text:''};stopPlayback()}const dbx=await db();await new Promise((resolve,reject)=>{const t=dbx.transaction(STORE,'readwrite'),o=t.objectStore(STORE);(d.sentences||[]).forEach(s=>{if(s.audioKey)o.delete(s.audioKey);o.delete(`${id}:${s.sentenceId}`)});t.oncomplete=resolve;t.onerror=()=>reject(t.error)});if(state.directoryHandle){try{const safe=d.title.replace(/[\\/:*?"<>|]/g,'_').slice(0,60)||'未命名稿件';for(const s of d.sentences||[])await state.directoryHandle.removeEntry(`${safe}-${String(s.sentenceIndex+1).padStart(2,'0')}-${s.sentenceId}.webm`);try{await state.directoryHandle.removeEntry(safe,{recursive:true})}catch(e){}}catch(e){}}render();notify('稿件和对应录音已删除')}
function bind(){ $('#settingsBtn')?.addEventListener('click',()=>{stopPlayback();state.screen='settings';render()});$('#settingsBack')?.addEventListener('click',()=>{state.screen='home';render()});$('#saveAsr')?.addEventListener('click',()=>{const endpoint=$('#asrEndpointInput').value.trim();if(!endpoint){notify('请输入 ASR 服务地址');return}try{new URL(endpoint)}catch(e){notify('请输入有效的 URL');return}state.asrEndpoint=endpoint;localStorage.setItem(ASR_CONFIG_KEY,JSON.stringify({endpoint}));notify('ASR 配置已保存')});$('#resetAsr')?.addEventListener('click',()=>{state.asrEndpoint='';localStorage.removeItem(ASR_CONFIG_KEY);render();notify('已恢复默认 ASR 地址')});$('#newDraft')?.addEventListener('click',newDraft);$('#newDraftEmpty')?.addEventListener('click',newDraft);document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openDraft(b.dataset.open));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteDraft(b.dataset.delete));$('#chooseFolder')?.addEventListener('click',chooseFolder);document.querySelector('.brand')?.addEventListener('click',()=>{if(state.recording)return;stopPlayback();state.screen='home';render()});$('#parseBtn')?.addEventListener('click',startDraft);$('#script')?.addEventListener('input',e=>{state.text=e.target.value});$('#title')?.addEventListener('input',e=>state.title=e.target.value);
 document.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>{state.source=b.dataset.source;document.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});
 $('#startRecord')?.addEventListener('click',startRecording);$('#stopRecord')?.addEventListener('click',stopRecording);$('#playCurrent')?.addEventListener('click',()=>play(state.index));$('#rerecord')?.addEventListener('click',()=>{state.sentences[state.index].recordingStatus='未录制';state.sentences[state.index].duration=0;state.elapsed=0;persist();render()});$('#confirmNext')?.addEventListener('click',()=>{state.sentences[state.index].recordingStatus='已确认';persist();if(state.index<state.sentences.length-1){state.index++;state.elapsed=0;render()}else{state.screen='review';render()}});$('#saveExit')?.addEventListener('click',()=>{stopPlayback();if(state.liveMedia?.state==='recording')state.liveMedia.stop();persist();state.screen='home';render();notify('进度已保存')});
 $('#playAll')?.addEventListener('click',async()=>{for(let i=0;i<state.sentences.length;i++){const a=await play(i);if(a)await new Promise(resolve=>{a.addEventListener('ended',resolve,{once:true})})}});$('#confirmAll')?.addEventListener('click',()=>{const recorded=state.sentences.filter(s=>s.audioKey||s.recordingStatus==='已录制'||s.recordingStatus==='已确认');if(!recorded.length){notify('还没有可确认的录音');return}state.sentences.forEach(s=>{if(s.audioKey||s.recordingStatus==='已录制'||s.recordingStatus==='已确认')s.recordingStatus='已确认'});persist();render();notify('已确认全部已录制句子')});document.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>play(+b.dataset.play));document.querySelectorAll('[data-rerecord]').forEach(b=>b.onclick=()=>{state.index=+b.dataset.rerecord;state.screen='recorder';state.elapsed=0;render()});$('#backRecord')?.addEventListener('click',()=>{state.index=0;state.screen='recorder';render()});$('#enterStudio')?.addEventListener('click',()=>{state.index=0;state.screen='studio';render();setTimeout(()=>playPrompt(),100)});
 $('#mockToggle')?.addEventListener('change',e=>{state.mock=e.target.checked;if(!state.mock)notify('提示音结束后会采集现场语音并发送到本地 ASR 代理')});$('#replayPrompt')?.addEventListener('click',playPrompt);$('#markDone')?.addEventListener('click',()=>advance(true));$('#markIncomplete')?.addEventListener('click',()=>{if(state.liveMedia?.state==='recording')state.liveMedia.stop();stopPlayback();notify('当前句未完成，将重新播放提示音');playPrompt()});$('#studioPrev')?.addEventListener('click',()=>{stopPlayback();state.index--;render();playPrompt()});$('#studioExit')?.addEventListener('click',()=>{stopPlayback();if(state.liveMedia?.state==='recording')state.liveMedia.stop();state.screen='review';render()})}
 function newDraft(){state={...state,screen:'editor',draftId:null,createdAt:null,title:'我的新稿件',text:'',source:'my-voice',sentences:[],index:0,elapsed:0,recording:false};render()}
 function openDraft(id){let d=drafts().find(x=>x.id===id);if(!d)return;state={...state,...d,screen:d.sentences?.length?'review':'editor',index:0};render()}
 function startDraft(){let text=$('#script').value.trim(),title=$('#title').value.trim()||'未命名稿件';if(!text){notify('请先输入口播稿');return}state.title=title;state.text=text;state.draftId=state.draftId||((crypto.randomUUID&&crypto.randomUUID())||String(Date.now()));state.createdAt=state.createdAt||new Date().toISOString();let old=state.sentences;state.sentences=splitText(text).map((t,i)=>{let same=old.find(x=>x.sentenceText===t);return same||{sentenceId:((crypto.randomUUID&&crypto.randomUUID())||`${Date.now()}-${i}`),sentenceIndex:i,sentenceText:t,recordingStatus:'未录制',sourceType:'my-voice',startTime:null,endTime:null,matchScore:null,needsRerecord:false}});state.index=0;persist();state.screen='recorder';render()}
 async function startRecording(){if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){notify('当前浏览器不支持录音，请使用最新版 Chrome 或 Safari');return}try{state.elapsed=0;state.stream=await getMicStream();let types=['audio/webm;codecs=opus','audio/webm','audio/mp4','audio/ogg'];let mime=types.find(x=>MediaRecorder.isTypeSupported(x))||'';let chunks=[];state.media=new MediaRecorder(state.stream,mime?{mimeType:mime}:undefined);state.media.ondataavailable=e=>e.data.size&&chunks.push(e.data);state.media.onstop=async()=>{let blob=new Blob(chunks,{type:state.media.mimeType||'audio/webm'}),s=state.sentences[state.index];s.audioKey=`${state.draftId}:${s.sentenceId}`;s.duration=Date.now()-state.startedAt;s.recordedAt=new Date().toISOString();s.recordingStatus='已录制';await putAudio(s.audioKey,blob);await saveToFolder(blob,s);state.recording=false;clearInterval(state.timer);persist();notify('录音已保存');render()};state.media.start();state.recording=true;state.startedAt=Date.now();state.timer=setInterval(()=>{state.elapsed=Date.now()-state.startedAt;let t=$('.timer');if(t)t.textContent=`${formatTime(state.elapsed)}　● 正在录音`},200);render()}catch(e){notify('无法使用麦克风，请检查浏览器权限')}}
 async function startLiveCapture(){if(state.mock||!navigator.mediaDevices?.getUserMedia)return;try{const stream=await getMicStream();const mime=['audio/webm;codecs=opus','audio/webm','audio/mp4'].find(x=>MediaRecorder.isTypeSupported(x))||'';state.liveChunks=[];state.liveMedia=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);state.liveMedia.ondataavailable=e=>e.data.size&&state.liveChunks.push(e.data);state.liveMedia.start()}catch(e){notify('无法启动现场 ASR 采集，将继续使用按钮模拟')}}
 async function finishLive(){if(!state.liveMedia)return true;return new Promise(resolve=>{const m=state.liveMedia;m.onstop=async()=>{m.stream.getTracks().forEach(t=>t.stop());const blob=new Blob(state.liveChunks,{type:m.mimeType||'audio/webm'});try{const r=await fetch('/api/asr',{method:'POST',headers:{'Content-Type':blob.type},body:blob});const data=await r.json();if(!r.ok)throw new Error(data.error||'ASR 请求失败');const text=(data.transcript||data.result?.text||data.result?.utterances?.map(x=>x.text).join('')||'').replace(/\s/g,'');const target=state.sentences[state.index].sentenceText.replace(/\s/g,'');if(text&&target.slice(0,Math.max(2,Math.floor(target.length*.55)))&&text.includes(target.slice(0,Math.max(2,Math.floor(target.length*.55))))){resolve(true)}else{resolve(false)}}catch(e){notify(`ASR 暂不可用：${e.message}`);resolve(true)}};if(m.state==='recording')m.stop();else resolve(true)})}
 function stopRecording(){if(state.media&&state.recording){state.media.stop();state.elapsed=Date.now()-state.startedAt}}
 async function playPrompt(){if(!state.audioUnlocked){notify('请先点击“开始口播”解锁手机音频');return}stopRecognition();state.studioPlaying=true;render();let a=await play(state.index);if(a)a.onended=()=>{state.studioPlaying=false;render()};else{state.studioPlaying=false;render()}}
 async function advance(done,force=false){if(done){stopRecognition();if(state.index<state.sentences.length-1){state.index++;render();playPrompt()}else{persist();notify('太棒了，整篇口播完成！');state.studioPlaying=false;setTimeout(()=>{state.screen='home';render()},900)}}}
async function removeIfExists(handle,name,options){try{await handle.removeEntry(name,options)}catch(e){}}
async function deleteDraft(id){const d=drafts().find(x=>x.id===id);if(!d||!confirm(`确定删除稿件“${d.title}”及其全部录音吗？`))return;localStorage.setItem(DRAFTS_KEY,JSON.stringify(drafts().filter(x=>x.id!==id)));if(state.draftId===id){stopPlayback();stopRecognition();releaseMic();localStorage.removeItem(DRAFT_KEY);state={...state,screen:'home',draftId:null,sentences:[],text:'',promptUrls:{}}}const dbx=await db();await new Promise((resolve,reject)=>{const t=dbx.transaction(STORE,'readwrite'),o=t.objectStore(STORE);(d.sentences||[]).forEach(s=>{o.delete(`${id}:${s.sentenceId}`);o.delete(`${d.title}:${s.sentenceId}`);if(s.audioKey)o.delete(s.audioKey)});t.oncomplete=resolve;t.onerror=()=>reject(t.error)});if(state.directoryHandle){const safe=d.title.replace(/[\\/:*?"<>|]/g,'_').slice(0,60)||'未命名稿件';for(const s of d.sentences||[]){const n=String(s.sentenceIndex+1).padStart(2,'0');await removeIfExists(state.directoryHandle,`${safe}-${n}-${s.sentenceId}.webm`)}try{const oldDir=await state.directoryHandle.getDirectoryHandle(safe);for(const s of d.sentences||[])await removeIfExists(oldDir,`${String(s.sentenceIndex+1).padStart(2,'0')}-${s.sentenceId}.webm`);await removeIfExists(state.directoryHandle,safe,{recursive:true})}catch(e){}}render();notify('稿件和对应录音已全部删除')}
 load();render();
